CREATE DATABASE BDVENDAS;

USE BDVENDAS;

CREATE TABLE CLIENTE (
CODCLIENTE INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR (30),
CIDADE VARCHAR (30),
UF CHAR(2),
CONSTRAINT pk_CodCliente PRIMARY KEY (CODCLIENTE),
INDEX idx_cliente (CODCLIENTE));

CREATE TABLE PRODUTOS (
CODPROD INT NOT NULL AUTO_INCREMENT,
DESCRICAO VARCHAR (30),
PRECOVENDA FLOAT,
CONSTRAINT pk_CodProd PRIMARY KEY (CODPROD),
INDEX idx_CodProd (CODPROD));

CREATE TABLE CABECALHO_PEDIDO (
NUMPEDIDO INT NOT NULL AUTO_INCREMENT,
DATAEMISSAO DATETIME,
CODCLIENTE INT,
VALORTOTAL FLOAT,
CONSTRAINT pk_NumPedido PRIMARY KEY (NUMPEDIDO),
INDEX idx_NumPedido (NUMPEDIDO),
CONSTRAINT fk_Cliente FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTE (CODCLIENTE));

CREATE TABLE ITENS_PEDIDO (
IDITEM INT NOT NULL AUTO_INCREMENT,
NUMPEDIDO INT,
CODPROD INT,
QUANTIDADE INT,
VLRUNITARIO FLOAT,
VLRTOTAL FLOAT,
CONSTRAINT pk_IdItem PRIMARY KEY (IDITEM),
CONSTRAINT fk_Pedido FOREIGN KEY (NUMPEDIDO) REFERENCES CABECALHO_PEDIDO (NUMPEDIDO),
CONSTRAINT fk_Produto FOREIGN KEY (CODPROD) REFERENCES PRODUTOS (CODPROD), 
INDEX idx_NumPedido (NUMPEDIDO));


INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Arnaldo', 'Betim', 'MG');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Aroldo','Ibirité', 'MG');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Atos', 'Brumadinho', 'MG');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Beatriz', 'Sarzedo', 'MG');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Bianca', 'Mario Campos', 'MG');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Bruna', 'Ibirité', 'MG');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Bruno', 'Sarzedo', 'MG');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Breno', 'Barreiro', 'MG');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Caio', 'Sarzedo', 'MG');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Carlos', 'Guarulhos', 'SP');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Carla', 'Montes Claros', 'MG');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Clarisse', 'Sarzedo', 'MG');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Camila', 'Osasco', 'SP');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Luiza', 'Ibirité', 'MG');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Marina', 'Sarzedo', 'MG');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Mariana', 'Belo Horizonte', 'MG');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Maria', 'Mauá', 'SP');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Marcos', 'Sarzedo', 'MG');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('Samara', 'Ibirité', 'MG');
INSERT INTO CLIENTE (NOME, CIDADE, UF) VALUES ('William', 'Sarzedo', 'MG');

INSERT INTO PRODUTOS (DESCRICAO, PRECOVENDA) VALUES ('Monitor 15.6'' preto', 710.00);
INSERT INTO PRODUTOS (DESCRICAO, PRECOVENDA) VALUES ('Monitor 18.5'' grafit', 650.91);
INSERT INTO PRODUTOS (DESCRICAO, PRECOVENDA) VALUES ('Teclado mecânico Dell', 1000.00);
INSERT INTO PRODUTOS (DESCRICAO, PRECOVENDA) VALUES ('Teclado comum preto', 100.00);
INSERT INTO PRODUTOS (DESCRICAO, PRECOVENDA) VALUES ('Teclado gamer branco', 940.00);
INSERT INTO PRODUTOS (DESCRICAO, PRECOVENDA) VALUES ('Mouse sem fio preto', 530.50);
INSERT INTO PRODUTOS (DESCRICAO, PRECOVENDA) VALUES ('Mouse sem fio gamer', 719.00);
INSERT INTO PRODUTOS (DESCRICAO, PRECOVENDA) VALUES ('Mouse comum Dell', 150.00);
INSERT INTO PRODUTOS (DESCRICAO, PRECOVENDA) VALUES ('Cadeira de escritório', 600.00);
INSERT INTO PRODUTOS (DESCRICAO, PRECOVENDA) VALUES ('Cadeira reclinável', 810.00);
INSERT INTO PRODUTOS (DESCRICAO, PRECOVENDA) VALUES ('Cadeira gamer comum', 790.99);
INSERT INTO PRODUTOS (DESCRICAO, PRECOVENDA) VALUES ('Cadeira gamer ajustável', 960.00);
INSERT INTO PRODUTOS (DESCRICAO, PRECOVENDA) VALUES ('Apoio para os pés', 150.00);
INSERT INTO PRODUTOS (DESCRICAO, PRECOVENDA) VALUES ('Apoio para os pés ajustável', 360.00);
INSERT INTO PRODUTOS (DESCRICAO, PRECOVENDA) VALUES ('Caneca comum gamer', 56.00);
INSERT INTO PRODUTOS (DESCRICAO, PRECOVENDA) VALUES ('Caneca personalizada', 90.00);
INSERT INTO PRODUTOS (DESCRICAO, PRECOVENDA) VALUES ('Copo térmico', 150.00);
INSERT INTO PRODUTOS (DESCRICAO, PRECOVENDA) VALUES ('Fone de ouvido comum', 59.00);
INSERT INTO PRODUTOS (DESCRICAO, PRECOVENDA) VALUES ('Fone de ouvido sem fio', 80.50);
INSERT INTO PRODUTOS (DESCRICAO, PRECOVENDA) VALUES ('Fone de ouvido gamer', 260.00);

